### ISSUE TITLE
Front-end MVP

### ISSUE THREAD

**Issue by vgeorge** [developmentseed/osm-gradient#10]
A list of issues and desired features for the front-end MVP:

- [x] Update map data on pan
- [x] Add satellite imagery
- [x] Add stats panel
- [ ] Block data fetching on lower zoom levels
- [ ] #33
- [x] Add time slider
- [x] Add geocoder
- [x] Fix popup

@wrynearson @LanesGood @sunu @kamicut feel please free to modify the list.

**Comment by LanesGood** [comment]
- [ ] Remove timeframe interface until time selection is available
- [x] Get + display AOI size
- [x] Swap users and tags
- [x] Hide users and tags beyond top ~5
- [x] Enable "See more" for users and tags

**Comment by kamicut** [comment]
MVP released at https://gradient.osmcha.org
