### ISSUE TITLE
Add production website, update staging

### ISSUE THREAD

**Issue by vgeorge** [developmentseed/osm-gradient#41]
In preparation for the presentation at SotM US 2024, it would be nice to setup a production URL for the website and rename the staging URL.

To do:

- [x] decide which URL to use for the production website
- [x] add workflow to deploy the main branch to production
- [x] update workflow to deploy the develop branch to staging
- [x] rename staging URL to osm-gradient.surge.sh

cc @kamicut

**Comment by vgeorge** [comment]
The CI is configured now to deploy the staging website to https://osm-gradient.surge.sh.

cc @kamicut @willemarcel

**Comment by kamicut** [comment]
Addressed using new preview and deploy workflow ymls
